### PR TITLE
Added some more (mostly steam scams)

### PR DESCRIPTION
**Pull request by slotling**
hi

### CODE REVIEW

**Comment by slotling** [comment]
i can sort all of them in alphabetical order if you want

**Comment by 45i** [comment]
> 
> 
> i can sort all of them in alphabetical order if you want

That'll be great thank u

**Comment by slotling** [comment]
> That'll be great thank u

Sure i will later

**Comment by 45i** [comment]
> 
> 
> > That'll be great thank u
> 
> Sure i will later

Great!

**Pull request merged**
